### PR TITLE
bug: Add missing dob for defendant (CMC-574)

### PR DESCRIPTION
**Pull request by sabahirfan**
### JIRA link (if applicable) ###
[CMC-574](https://tools.hmcts.net/jira/browse/CMC-574)

### Change description ###
This PR implements the missing date of birth in defendant details screen for individual and sole trader type of defendant party. And we are also making DOB optional for both parties as per Darren.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by ckalista — CHANGES_REQUESTED** [review]
I think Darren stated that DOB fields for both claimant and defendant should be optional.

Also we probably want to tweak out e2e to capture a DOB.

**Review by ckalista — APPROVED** [review]

**Review by dharmendrak — APPROVED** [review]
LGTM

**Comment by swalker125** [comment]
@sabahirfan @ckalista I do not agree with this being a bug. Date of birth was purposefully left out as it was not in the AC of a ticket. It was pointed out to me in QA. I would rename PR type.

**Comment by ckalista** [comment]
@swalker125 I spotted this discrepancy just by chance and at the time raised it as a bug as thought it odd it was left out. Let's not do anything on this until we have got final confirmation what to do with this DOB.

**Comment by swalker125** [comment]
@ckalista comment in question for your reference https://tools.hmcts.net/jira/browse/CMC-28?focusedCommentId=804241&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-804241

**Comment by sabahirfan** [comment]
This is not required anymore.

**Pull request closed without merging**
